name: github-actions

on:
  push:
    branches:
      - authApp-tests

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run eslint
      run: npx eslint .

    - name: Run Jest tests
      run: npx jest

    - name: Cleanup
      run: npm run cleanup
    
